"""add plays.season

Revision ID: 0891bd8f6640
Revises: 82291d66666d
Create Date: 2026-07-18 23:05:18.068315
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0891bd8f6640'
down_revision: str | None = '82291d66666d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plays_season'), ['season'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plays_season'))
        batch_op.drop_column('season')

    # ### end Alembic commands ###
