"""add betting_lines

Revision ID: 3bf93f3f3c23
Revises: 0891bd8f6640
Create Date: 2026-07-19 00:31:57.324114
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf93f3f3c23'
down_revision: str | None = '0891bd8f6640'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('formatted_spread', sa.String(length=64), nullable=True),
    sa.Column('over_under', sa.Float(), nullable=True),
    sa.Column('home_moneyline', sa.Integer(), nullable=True),
    sa.Column('away_moneyline', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'provider', name='uq_betting_line')
    )
    with op.batch_alter_table('betting_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_lines_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betting_lines_season'), ['season'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_lines_season'))
        batch_op.drop_index(batch_op.f('ix_betting_lines_game_id'))

    op.drop_table('betting_lines')
    # ### end Alembic commands ###
