"""add recruiting and transfers

Revision ID: 44e2228ff5b5
Revises: 3bf93f3f3c23
Create Date: 2026-07-19 01:13:18.841956
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e2228ff5b5'
down_revision: str | None = '3bf93f3f3c23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_recruiting_ranks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team', name='uq_team_recruiting')
    )
    with op.batch_alter_table('team_recruiting_ranks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_recruiting_ranks_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_recruiting_ranks_team'), ['team'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=160), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_season'), ['season'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_season'))
        batch_op.drop_index(batch_op.f('ix_transfers_origin'))
        batch_op.drop_index(batch_op.f('ix_transfers_destination'))

    op.drop_table('transfers')
    with op.batch_alter_table('team_recruiting_ranks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_recruiting_ranks_team'))
        batch_op.drop_index(batch_op.f('ix_team_recruiting_ranks_season'))

    op.drop_table('team_recruiting_ranks')
    # ### end Alembic commands ###
