"""initial schema

Revision ID: 82291d66666d
Revises: 
Create Date: 2026-07-18 22:02:51.083139
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82291d66666d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=96), nullable=True),
    sa.Column('last_name', sa.String(length=96), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('jersey', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('home_city', sa.String(length=96), nullable=True),
    sa.Column('home_state', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_team'), ['team'], unique=False)

    op.create_table('rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=16), nullable=True),
    sa.Column('poll', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('conference', sa.String(length=64), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('first_place_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'week', 'season_type', 'poll', 'team', name='uq_ranking')
    )
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rankings_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_team'), ['team'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('school', sa.String(length=128), nullable=False),
    sa.Column('mascot', sa.String(length=128), nullable=True),
    sa.Column('abbreviation', sa.String(length=16), nullable=True),
    sa.Column('conference', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('alt_color', sa.String(length=16), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_conference'), ['conference'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_school'), ['school'], unique=False)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('grass', sa.Boolean(), nullable=True),
    sa.Column('dome', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=16), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('neutral_site', sa.Boolean(), nullable=True),
    sa.Column('conference_game', sa.Boolean(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=128), nullable=True),
    sa.Column('home_conference', sa.String(length=64), nullable=True),
    sa.Column('home_points', sa.Integer(), nullable=True),
    sa.Column('away_id', sa.Integer(), nullable=True),
    sa.Column('away_team', sa.String(length=128), nullable=True),
    sa.Column('away_conference', sa.String(length=64), nullable=True),
    sa.Column('away_points', sa.Integer(), nullable=True),
    sa.Column('excitement_index', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_away_id'), ['away_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_home_id'), ['home_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_week'), ['week'], unique=False)

    op.create_table('drives',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('offense', sa.String(length=128), nullable=True),
    sa.Column('defense', sa.String(length=128), nullable=True),
    sa.Column('drive_number', sa.Integer(), nullable=True),
    sa.Column('scoring', sa.Boolean(), nullable=True),
    sa.Column('start_period', sa.Integer(), nullable=True),
    sa.Column('start_yardline', sa.Integer(), nullable=True),
    sa.Column('start_yards_to_goal', sa.Integer(), nullable=True),
    sa.Column('end_period', sa.Integer(), nullable=True),
    sa.Column('end_yardline', sa.Integer(), nullable=True),
    sa.Column('end_yards_to_goal', sa.Integer(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('yards', sa.Integer(), nullable=True),
    sa.Column('drive_result', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drives_game_id'), ['game_id'], unique=False)

    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('player', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('stat_type', sa.String(length=32), nullable=False),
    sa.Column('stat', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'category', 'stat_type', name='uq_player_game_stat')
    )
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_stats_team'), ['team'], unique=False)

    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('stat_type', sa.String(length=48), nullable=False),
    sa.Column('stat', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team', 'stat_type', name='uq_team_game_stat')
    )
    with op.batch_alter_table('team_game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_game_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_game_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_game_stats_team'), ['team'], unique=False)

    op.create_table('plays',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('drive_id', sa.BigInteger(), nullable=True),
    sa.Column('drive_number', sa.Integer(), nullable=True),
    sa.Column('play_number', sa.Integer(), nullable=True),
    sa.Column('offense', sa.String(length=128), nullable=True),
    sa.Column('defense', sa.String(length=128), nullable=True),
    sa.Column('offense_score', sa.Integer(), nullable=True),
    sa.Column('defense_score', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('clock_minutes', sa.Integer(), nullable=True),
    sa.Column('clock_seconds', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('yard_line', sa.Integer(), nullable=True),
    sa.Column('yards_to_goal', sa.Integer(), nullable=True),
    sa.Column('yards_gained', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.String(length=64), nullable=True),
    sa.Column('play_text', sa.Text(), nullable=True),
    sa.Column('scoring', sa.Boolean(), nullable=True),
    sa.Column('points_scored', sa.Integer(), nullable=True),
    sa.Column('ppa', sa.Float(), nullable=True),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('wp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plays_drive_id'), ['drive_id'], unique=False)
        batch_op.create_index('ix_plays_game_drive', ['game_id', 'drive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_offense'), ['offense'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_play_type'), ['play_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_scoring'), ['scoring'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_yards_to_goal'), ['yards_to_goal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plays_yards_to_goal'))
        batch_op.drop_index(batch_op.f('ix_plays_scoring'))
        batch_op.drop_index(batch_op.f('ix_plays_play_type'))
        batch_op.drop_index(batch_op.f('ix_plays_offense'))
        batch_op.drop_index(batch_op.f('ix_plays_game_id'))
        batch_op.drop_index('ix_plays_game_drive')
        batch_op.drop_index(batch_op.f('ix_plays_drive_id'))

    op.drop_table('plays')
    with op.batch_alter_table('team_game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_game_stats_team'))
        batch_op.drop_index(batch_op.f('ix_team_game_stats_season'))
        batch_op.drop_index(batch_op.f('ix_team_game_stats_game_id'))

    op.drop_table('team_game_stats')
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_stats_team'))
        batch_op.drop_index(batch_op.f('ix_player_game_stats_season'))
        batch_op.drop_index(batch_op.f('ix_player_game_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_stats_game_id'))

    op.drop_table('player_game_stats')
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drives_game_id'))

    op.drop_table('drives')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_week'))
        batch_op.drop_index(batch_op.f('ix_games_season'))
        batch_op.drop_index(batch_op.f('ix_games_home_id'))
        batch_op.drop_index(batch_op.f('ix_games_away_id'))

    op.drop_table('games')
    op.drop_table('venues')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_school'))
        batch_op.drop_index(batch_op.f('ix_teams_conference'))

    op.drop_table('teams')
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rankings_team'))
        batch_op.drop_index(batch_op.f('ix_rankings_season'))

    op.drop_table('rankings')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team'))

    op.drop_table('players')
    # ### end Alembic commands ###
