"""add coach_seasons

Revision ID: 8b8aaa3bf7f1
Revises: aa8dce1512da
Create Date: 2026-07-19 14:52:54.280983
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8aaa3bf7f1'
down_revision: str | None = 'aa8dce1512da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach', sa.String(length=160), nullable=False),
    sa.Column('first_name', sa.String(length=96), nullable=True),
    sa.Column('last_name', sa.String(length=96), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach', 'team', 'season', name='uq_coach_season')
    )
    with op.batch_alter_table('coach_seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_seasons_coach'), ['coach'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_seasons_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_seasons_team'), ['team'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_seasons_team'))
        batch_op.drop_index(batch_op.f('ix_coach_seasons_season'))
        batch_op.drop_index(batch_op.f('ix_coach_seasons_coach'))

    op.drop_table('coach_seasons')
    # ### end Alembic commands ###
