"""add opening lines for clv

Revision ID: 9be7a3bc7140
Revises: 8b8aaa3bf7f1
Create Date: 2026-07-19 14:59:28.069284
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be7a3bc7140'
down_revision: str | None = '8b8aaa3bf7f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spread_open', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('over_under_open', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_lines', schema=None) as batch_op:
        batch_op.drop_column('over_under_open')
        batch_op.drop_column('spread_open')

    # ### end Alembic commands ###
