"""add plays wpa

Revision ID: aa8dce1512da
Revises: 44e2228ff5b5
Create Date: 2026-07-19 14:49:29.163881
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8dce1512da'
down_revision: str | None = '44e2228ff5b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wpa_player', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_plays_wpa_player'), ['wpa_player'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plays_wpa_player'))
        batch_op.drop_column('wpa_player')
        batch_op.drop_column('wpa')

    # ### end Alembic commands ###
